import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:codegraph/src/daemon.dart' as daemon_api;
import 'package:codegraph/src/engine.dart' as engine;
import 'package:test/test.dart';

import 'fixture.dart';

void main() {
  final repoRoot = Directory.current.absolute.path;
  final originalCwd = Directory.current;
  late Directory tempDir;
  Process? daemon;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('codegraph_daemon_');
    writeCodegraphFixture(tempDir);
    Directory.current = tempDir;
  });

  tearDown(() async {
    if (daemon != null) {
      await daemon_api.run(['stop']);
      try {
        await daemon!.exitCode.timeout(const Duration(seconds: 5));
      } on TimeoutException {
        daemon!.kill();
      }
    }
    Directory.current = originalCwd;
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  test('one event-driven worker refreshes the graph without map churn',
      () async {
    engine.build(const []);
    final markdownBefore = {
      for (final file in Directory('${tempDir.path}/docs/maps')
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.md')))
        file.path: file.readAsBytesSync(),
    };

    daemon = await Process.start(
      Platform.resolvedExecutable,
      ['$repoRoot/bin/codegraph.dart', 'daemon'],
      workingDirectory: tempDir.path,
    );
    final stderr = StringBuffer();
    daemon!.stderr.transform(utf8.decoder).listen(stderr.write);
    final ready = await daemon!.stdout
        .transform(utf8.decoder)
        .transform(const LineSplitter())
        .first
        .timeout(const Duration(seconds: 20));
    expect(ready, contains('daemon listening'));

    expect(await daemon_api.run(const []), 0);

    File('${tempDir.path}/lib/home/home_page.dart').writeAsStringSync(
      '\nclass DaemonCanary {}\n',
      mode: FileMode.append,
    );
    expect(await daemon_api.syncIfRunning(), isTrue, reason: stderr.toString());
    final graph = jsonDecode(
      File('${tempDir.path}/docs/maps/code_graph.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    expect(
      (graph['nodes'] as List).any(
        (node) => ((node as Map)['symbols'] as List? ?? const [])
            .any((symbol) => (symbol as Map)['n'] == 'DaemonCanary'),
      ),
      isTrue,
    );

    for (final entry in markdownBefore.entries) {
      expect(File(entry.key).readAsBytesSync(), entry.value,
          reason: '${entry.key} must not be regenerated by the daemon');
    }
    expect(await daemon_api.run(const ['status']), 0);

    expect(await daemon_api.run(const ['stop']), 0);
    expect(
      await daemon!.exitCode.timeout(const Duration(seconds: 5)),
      0,
      reason: stderr.toString(),
    );
    daemon = null;
    expect(
      File('${tempDir.path}/.dart_tool/codegraph/daemon.json').existsSync(),
      isFalse,
    );
  }, timeout: const Timeout(Duration(seconds: 40)));
}
