// Markdown map writer (extracted from engine.dart, pure refactor — zero
// behavior change). Owns rendering of `docs/maps/<area>.md` (Summary-only,
// 0.6.0 Stage 2) and `docs/maps/INDEX.md`.
//
// Imports `engine.dart` for the shared registry types (`FileInfo`,
// `ProviderDecl`) rather than the reverse — those types are core-registry
// concerns engine.dart's non-markdown code (provider resolution, graph
// writing) also depends on, so keeping them there and importing them here
// mirrors the `nav_resolution.dart` pattern.
import 'dart:io';

import 'engine.dart' show FileInfo;
import 'resolution.dart' show ProviderDecl;

/// `chars / 4` rounded to the nearest 100, rendered `X.Yk` (e.g. `4.3k`),
/// or `0.3k` for anything under 1k — one format, always one decimal.
String _tokenLabel(int chars) {
  final tokens = ((chars / 4 / 100).round() * 100);
  return '${(tokens / 1000).toStringAsFixed(1)}k';
}

void writeAllAreaMaps(
  List<FileInfo> all,
  Map<String, ProviderDecl> providers,
  Map<String, int> readerCounts,
) {
  final areas = <String, List<FileInfo>>{};
  for (final i in all) {
    final segs = i.libPath.split('/');
    if (segs.length < 3) continue; // need lib/<area>/... or packages/<pkg>/...
    areas.putIfAbsent('${segs[0]}/${segs[1]}', () => []).add(i);
  }
  final keys = areas.keys.toList()..sort();
  final index = StringBuffer()
    ..writeln('# Code map index')
    ..writeln()
    ..writeln(
      '_Generated by `codegraph build` — these maps are Summary-only '
      '(counts, top providers, entry pages, cross-area consumers) for '
      'browsing on GitHub; `codegraph brief <area>` is the primary way to '
      'orient on an area (fresh, budgeted, full detail). Whole-repo '
      'queryable graph: `code_graph.json` (query via '
      '`codegraph find|readers|wiring|impls|path`). Still grep for: exact '
      'strings and implementation syntax._',
    )
    ..writeln()
    ..writeln('| Area | files | providers | ~tokens | map |')
    ..writeln('|------|------:|----------:|--------:|-----|');
  var written = 0;
  for (final area in keys) {
    final scoped = areas[area]!;
    if (scoped.length < 2) continue;
    final name = area.split('/').last;
    final prefix = '$area/';
    final outPath = 'docs/maps/$name.md';
    final rendered = _renderMarkdown(scoped, providers, prefix, readerCounts);
    File(outPath)
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(rendered);
    final provCount = scoped.fold<int>(0, (s, i) => s + i.providerDecls.length);
    index.writeln(
      '| `$area` | ${scoped.length} | $provCount | ${_tokenLabel(rendered.length)} '
      '| [$name.md]($name.md) |',
    );
    written++;
  }
  File('docs/maps/INDEX.md').writeAsStringSync(index.toString());
  stderr.writeln('wrote $written area maps + docs/maps/INDEX.md');
}

/// Cross-feature providers consumed by [infos] but declared outside
/// [prefix]: name -> declaring file. Shared by the `## Summary` section
/// (top 10) and the full `## Cross-feature providers consumed` list.
Map<String, String> _external(
  List<FileInfo> infos,
  Map<String, ProviderDecl> providers,
  String prefix,
) {
  final external = <String, String>{};
  for (final i in infos) {
    for (final name in {
      ...i.watches.keys,
      ...i.reads.keys,
      ...i.listens.keys
    }) {
      final decl = providers[name];
      if (decl != null && !decl.file.startsWith(prefix)) {
        external[name] = decl.file;
      }
    }
  }
  return external;
}

/// `## Summary`: counts, providers by reader count (top 10,
/// project-wide via [readerCounts]), entry pages (role=view with navigates,
/// top 8), cross-area providers consumed (top 10, reuses [_external]).
/// Deterministic: count desc then name asc.
void _writeSummary(
  StringBuffer b,
  List<FileInfo> infos,
  Map<String, ProviderDecl> providers,
  Map<String, int> readerCounts,
  String prefix,
) {
  String rel(String libPath) => libPath.replaceFirst(prefix, '');
  b
    ..writeln('## Summary')
    ..writeln()
    ..writeln('- Files: ${infos.length}')
    ..writeln(
      '- Providers declared: '
      '${infos.fold<int>(0, (s, i) => s + i.providerDecls.length)}',
    )
    ..writeln();

  final declaredHere = <String>{
    for (final i in infos) ...i.providerDecls.map((p) => p.name)
  };
  final ranked =
      declaredHere.map((n) => MapEntry(n, readerCounts[n] ?? 0)).toList()
        ..sort((a, b) {
          final byCount = b.value.compareTo(a.value);
          return byCount != 0 ? byCount : a.key.compareTo(b.key);
        });
  b.writeln(
    ranked.isEmpty
        ? '- Providers by reader count: (none)'
        : '- Providers by reader count: '
            '${ranked.take(10).map((e) => '${e.key} ·${e.value}').join(', ')}'
            '${ranked.length > 10 ? ', … ${ranked.length - 10} more' : ''}',
  );

  final entryPages = infos
      .where((i) => i.role == 'view' && i.navigates.isNotEmpty)
      .map((i) => rel(i.libPath))
      .toList()
    ..sort();
  b.writeln(
    entryPages.isEmpty
        ? '- Entry pages: (none)'
        : '- Entry pages: '
            '${entryPages.take(8).map((p) => '`$p`').join(', ')}'
            '${entryPages.length > 8 ? ', … ${entryPages.length - 8} more' : ''}',
  );

  final external = _external(infos, providers, prefix);
  final crossKeys = external.keys.toList()..sort();
  b.writeln(
    crossKeys.isEmpty
        ? '- Cross-area providers consumed: (none)'
        : '- Cross-area providers consumed: '
            '${crossKeys.take(10).map((k) => '`$k` ← `${external[k]}`').join(', ')}'
            '${crossKeys.length > 10 ? ', … ${crossKeys.length - 10} more' : ''}',
  );
  b.writeln();
}

void writeMarkdown(
  List<FileInfo> infos,
  Map<String, ProviderDecl> providers,
  String prefix,
  String outPath,
  Map<String, int> readerCounts,
) {
  final content = _renderMarkdown(infos, providers, prefix, readerCounts);
  final out = File(outPath);
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(content);
}

String _renderMarkdown(
  List<FileInfo> infos,
  Map<String, ProviderDecl> providers,
  String prefix,
  Map<String, int> readerCounts,
) {
  final b = StringBuffer();
  b
    ..writeln('# Code map: `${prefix.substring(0, prefix.length - 1)}`')
    ..writeln()
    // No timestamp here either — same reason as code_graph.json's
    // `generatedAt` above: this file is content-diffed by `check()`.
    ..writeln('_Generated by `codegraph build` — do not edit._')
    ..writeln();

  _writeSummary(b, infos, providers, readerCounts, prefix);

  b.writeln(
    '_Full detail: `codegraph brief ${prefix.substring(0, prefix.length - 1)}` '
    '· `wiring <file>` · `sym <Symbol>` · `skeleton <file>`._',
  );

  return b.toString();
}
